package com.Exception;

public class ExceptionHandling {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		try {
			int a = 5;
			int b =0;
			int c = a/b;
					System.out.println(c);
			
		}
		catch(ArithmeticException e) {
			String message = e.getMessage();
		System.out.println(message);
		
		}
	}

}
